ecom/accounts/urls.py
from django.urls import path,include
from accounts.views import login_page,register_page , activate_email
from .views import *
from django.contrib.auth import views as auth_views
urlpatterns = [
   path('login/' , login_page , name="login" ),
   path('register/' , register_page , name="register"),
   path('logout/', logout_view, name='logout'),
  
   path('activate/<email_token>/' , activate_email , name="activate_email"),
   
   path('add_to_cart/<uid>/',add_to_cart,name='add_to_cart'),
   path('cart',cart,name="cart"),
   path('remove_cart/<cart_item_uid>/',remove_cart,name='remove_cart'),
   path('remove_coupon/<cart_id>/',remove_coupon,name='remove_coupon'),
   
   path('create-checkout-session/', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
   
   path('success/', success_view, name='success'),
   path('track_status/',track_status,name='track_status'),
   path('cancel/', cancel_view, name='cancel'),
   
   path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
  #  path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
   path('password_reset/done/', password_reset_done, name='password_reset_done'),
   
   path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
   path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

  path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_change/done/', password_change_done, name='password_change_done'),
    
    path('filter_products/',filter,name='filter_products'),
    path('search/',search_products,name='search'),
     
     path('profile',profile,name='profile'),
     
    
]

ecom/ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    
    path('',include('home.urls')),
    path('product/',include('products.urls'))
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

ecom/accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from base.models import BaseModel
import uuid
from base.emails import send_account_activation_email
from products.models import Product,ColorVariant,SizeVariant,Coupon
class Profile(BaseModel):
    user=models.OneToOneField(User,on_delete=models.CASCADE,related_name='profile')
    is_email_verified=models.BooleanField(default=False)
    email_token=models.CharField(max_length=100,null=True,blank=True)
   
    profile_image=models.ImageField(upload_to='profile')
    address_line_1 = models.CharField(max_length=255, null=True, blank=True)
    address_line_2 = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    zip_code = models.CharField(max_length=20, null=True, blank=True)

    
    
    
    
    
    
    
    def get_first_name(self):
        return self.user.first_name

    def get_cart_count(self):
        return CartItems.objects.filter(cart__is_paid=False,cart__user=self.user).count()   
    
   
    
    
    
    
        
  
class Cart(BaseModel):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='carts')
    coupon=models.ForeignKey(Coupon,on_delete=models.SET_NULL,null=True,blank=True)
    is_paid=models.BooleanField(default=False)
    
    def get_cart_total(self):
        cart_items = CartItems.objects.filter(cart__is_paid=False, cart__user=self.user)
        price = [item.get_product_price() for item in cart_items]
        if self.coupon:
            if self.coupon.minimum_amount< sum(price):
                return sum(price)-self.coupon.discount_price

        return sum(price)
    
    
    
    
    
    
    
    
class CartItems(BaseModel):
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE,related_name='cart_items')
    product=models.ForeignKey(Product,on_delete=models.SET_NULL,null=True,blank=True)
    color_variant=models.ForeignKey(ColorVariant,on_delete=models.SET_NULL,blank=True,null=True)
    size_variant=models.ForeignKey(SizeVariant,on_delete=models.SET_NULL,blank=True,null=True)
    STATUS_CHOICES = (
        ('P', 'Packed'),
        ('D', 'Dispatched'),
        ('DL', 'Delivered'),
    )
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default='P') 
   
    
    def get_product_price(self):
        price=[self.product.price]
        if self.color_variant:
            color_variant_price=self.color_variant.price
            price.append(color_variant_price)
        if self.size_variant:
            size_variant_price=self.size_variant.price 
            price.append(size_variant_price)
        return sum(price)            
    
    
  
    
@receiver(post_save , sender = User)
def  send_email_token(sender , instance , created , **kwargs):
    try:
        if created:
            email_token = str(uuid.uuid4())
            Profile.objects.create(user = instance , email_token = email_token)
            Cart.objects.create(user=instance)
            email = instance.email
            send_account_activation_email(email , email_token)

    except Exception as e:
        print(e)
        
        

ecom/accounts/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_image', 'address_line_1', 'address_line_2', 'city', 'state', 'country', 'zip_code']
        
        
    
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['profile_image'].widget.attrs.update({'class': 'form-control d-none' })
        self.fields['address_line_1'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Address Line 1'})
        self.fields['address_line_2'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Address Line 2'})
        self.fields['city'].widget.attrs.update({'class': 'form-control', 'placeholder': 'City'})
        self.fields['state'].widget.attrs.update({'class': 'form-control', 'placeholder': 'State'})
        self.fields['country'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Country'})
        self.fields['zip_code'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Zip Code'})

ecom/accounts/views.py
from django.shortcuts import render,HttpResponseRedirect,redirect,HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from .models import Profile,Cart,CartItems
from products.models import *
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
import stripe
from django.views import View
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.template.loader import render_to_string
from .forms import ProfileForm
stripe.api_key = settings.STRIPE_SECRET_KEY



def login_page(request):
    if request.method=='POST':
        email=request.POST.get('email')
        password=request.POST.get('password')
        user_obj=User.objects.filter(username=email) 

        if  not user_obj.exists():
            messages.warning(request,'Account not found.')
            return HttpResponseRedirect(request.path_info)
        if not user_obj[0].profile.is_email_verified:
            messages.warning(request,'Your account is not verified')
            return HttpResponseRedirect(request.path_info)

        user_obj=authenticate(username=email,password=password)

        if user_obj:
            login(request,user_obj)
            return redirect('/')


        messages.warning(request,'Invalid Credentials')
        return HttpResponseRedirect(request.path_info)

    return render(request,'accounts/login.html')







def register_page(request):
    if request.method=='POST':
        first_name=request.POST.get('first_name')
        last_name=request.POST.get('last_name')
        email=request.POST.get('email')
        password=request.POST.get('password')
        user_obj=User.objects.filter(username=email) 

        if user_obj.exists():
            messages.warning(request,'Email is already taken.')
            return HttpResponseRedirect(request.path_info)

        try:
            # Validate the password
            validate_password(password)
        except ValidationError as e:
            messages.error(request, '\n'.join(e.messages))
            return HttpResponseRedirect(request.path_info)


        user_obj=User.objects.create(first_name=first_name,last_name=last_name,email=email,username=email)
        user_obj.set_password(password)
        user_obj.save()

        messages.success(request,'An email has been sent to your mail ')
        return HttpResponseRedirect(request.path_info)
    return render(request,'accounts/register.html')



@login_required
def logout_view(request):
    logout(request)
    return redirect('login')  # Assuming you have a URL named 'login' for the login page






def activate_email(request , email_token):
    try:
        user = Profile.objects.get(email_token= email_token)
        user.is_email_verified = True
        user.save()
        return redirect('login')
    except Exception as e:
        return HttpResponse('Invalid Email token')









@login_required       
def add_to_cart(request,uid):
    size=request.GET.get('size')
    color=request.GET.get('color')
    product=Product.objects.get(uid=uid)
    user=request.user
    cart,_=Cart.objects.get_or_create(user=user,is_paid=False)
    cart_item=CartItems.objects.create(cart=cart,product=product,)
    if size:
        size=request.GET.get('size')
        size_variant=SizeVariant.objects.get(size_name=size)

        cart_item.size_variant=size_variant
        cart_item.save()
    if color:
        color=request.GET.get('color')
        color_variant=ColorVariant.objects.get(color_name=color)

        cart_item.color_variant=color_variant
        cart_item.save()



    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def password_change_done(request):
    return render(request,'registration/password_change_done.html')





@login_required
def remove_cart(request,cart_item_uid):
    try:
        cart_item=CartItems.objects.get(uid=cart_item_uid)
        cart_item.delete()
    except Exception as  e:
        print(e)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))











@login_required
def cart(request):
    try:
        cart_obj = Cart.objects.get(is_paid=False, user=request.user)
    except Cart.DoesNotExist:
        cart_obj = None
    if request.method=='POST':
        coupon=request.POST.get('coupon')
        coupon_obj=Coupon.objects.filter(coupon_code__icontains=coupon)

        if not coupon_obj.exists():
            messages.warning(request,'Invalid Coupon')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))

        if cart_obj.coupon:
            messages.warning(request,'Coupon already exists.')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))

        if cart_obj.get_cart_total()<coupon_obj[0].minimum_amount:
           messages.warning(request,f'Amount should be greater than {coupon_obj[0].minimum_amount}.')
           return HttpResponseRedirect(request.META.get('HTTP_REFERER','/')) 

        if coupon_obj[0].is_expired:
            messages.warning(request,'Coupon Expired.')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))

        cart_obj.coupon =coupon_obj[0]
        cart_obj.save()
        messages.success(request,'Coupon applied!!')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))    

    context={'cart':cart_obj}
    return render(request, 'accounts/cart.html', context)




@login_required
def remove_coupon(request,cart_id):
    cart=Cart.objects.get(uid=cart_id)
    cart.coupon=None
    cart.save()

    messages.success(request,'Coupon removed!!')


    return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))    




@login_required
def success_view(request):
    messages.success(request, 'Your order has been placed successfully and will be delivered to you shortly')
    messages.success(request, 'Your order summary has been sent to you via email')

    session_id = request.GET.get('session_id')

    if session_id:
        checkout_session = stripe.checkout.Session.retrieve(session_id)
        if checkout_session.payment_status == 'paid':
            # Mark the cart as paid
            user = request.user
            carts = Cart.objects.filter(user=user, is_paid=False)

            for cart in carts:
                cart.is_paid = True
                cart.save()

            # Prepare email content with purchased items table
            subject = 'Order Confirmation'
            recipient_list = [user.email]

            # Get paid carts for the user
            paid_carts = Cart.objects.filter(user=request.user, is_paid=True)

            # Prepare data for the email template
            context = {
                'user': user,
                'paid_carts': paid_carts,
            }

            # Render the email template to string
            email_message = render_to_string('accounts/email_order_confirmation.html', context)

            # Send email
            send_mail(
                subject,
                email_message,
                settings.EMAIL_HOST_USER,
                recipient_list,
                html_message=email_message,  # Enable HTML content in the email
                fail_silently=False,
            )

    # Fetch all paid orders for the user to display in success.html
    paid_carts = Cart.objects.filter(user=request.user, is_paid=True)

    return render(request, 'accounts/success.html', {'paid_carts': paid_carts})



@login_required
def cancel_view(request):
    return render(request, 'accounts/cancel.html')






@login_required
def track_status(request):
    # Retrieve all purchased items for the user
    user = request.user
    purchased_items = CartItems.objects.filter(cart__user=user, cart__is_paid=True)

    return render(request, 'accounts/track_status.html', {'purchased_items': purchased_items})




class CreateCheckoutSessionView(View):

    def post(self, request):
        user = request.user
        carts = Cart.objects.filter(user=user, is_paid=False)


        if not carts:
            return JsonResponse({'error': 'No active carts found for the user'}, status=400)

        line_items = []

        for cart in carts:
            for cart_item in cart.cart_items.all():

                line_items.append({
                    'price_data': {
                        'currency': 'usd',
                        'unit_amount': int(cart_item.get_product_price() * 100),  # amount in cents
                        'product_data': {
                            'name': cart_item.product.product_name,

                        },
                    },
                    'quantity': 1,  # or cart_item.quantity if you have quantity field
                })

        YOUR_DOMAIN = 'http://127.0.0.1:8000/'
        checkout_session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=line_items,
            mode='payment',
            success_url=YOUR_DOMAIN + 'accounts/success/?session_id={CHECKOUT_SESSION_ID}',
            cancel_url=YOUR_DOMAIN + 'accounts/cancel/',
            billing_address_collection='required'

        )

        return JsonResponse({
            'id': checkout_session.id
        })








@login_required
class CustomPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('password_change_done')
    template_name = 'registration/password_change_form.html'



def filter(request):
    # Retrieve all categories
    categories = Category.objects.all()

    # Get the selected category from the request
    selected_category = request.GET.get('category')

    if selected_category:

ecom/templates/accounts/cancel.html
{% extends 'base/base.html'%}
{%  block start %}
<div class="container "style="height: 500px;">
<div class=" alert alert-danger mt-5 mb-5 "   role="alert">
    Your payment was cancelled Please try again!! Money will be refunded in two or three working days if deducted from the account
</div></div>
{% endblock %}

ecom/templates/accounts/cart.html
{% extends 'base/base.html'%}

{% block start %}

<script src="https://js.stripe.com/v3/"></script>

<section class="section-content padding-y ">
    <div class="container">

        <div class="row">
            <main class="col-md-9">
                <div class="card">
                    {% if cart.cart_items.all %}
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Size</th>
                                <th scope="col" width="180">Color option</th>

                                <th scope="col" width="120">Price</th>
                                <th scope="col" class="text-right" width="200"> </th>
                            </tr>
                        </thead>
                        <tbody>


                            {% for cart_item in cart.cart_items.all %}
                            <tr>
                                <td>
                                    <figure class="itemside">
                                        <div class="aside"><img
                                                src="{{ cart_item.product.product_images.first.image.url }}"
                                                class="img-sm"></div>
                                        <figcaption class="info">
                                            <a href="#" class="title text-dark">{{ cart_item.product.product_name }}</a>

                                            <p class="text-muted small">Price: ${{ cart_item.get_product_price }}</p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <span><a href="#" class="title text-dark">{{ cart_item.size_variant }}</a></span>
                                </td>
                                <td>
                                    <span><a href="#" class="title text-dark">{{ cart_item.color_variant }}</a></span>
                                </td>

                                <td>
                                    <div class="price-wrap">
                                        <var class="price">${{ cart_item.get_product_price }}</var>
                                    </div>
                                </td>
                                <td class="title text-dark">
                                    <a href="{% url 'remove_cart' cart_item.uid %}" class="btn btn-light">Remove</a>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}

                            <video src="/media/video/empty_cart.mp4" class="container w-50"></video>
                            <h1 class="container text-center">Empty cart !!</h1>
                            {% endif %}
                        </tbody>
                    </table>

                    {% if cart.cart_items.all %}
                    <div class="card-body border-top">
                        
                         
                                
                                
                        <a href="{% url 'index' %}" class="btn btn-light"> <i class="fa fa-chevron-left"></i> Continue shopping </a>
                        <button type="button" class="btn btn-primary float-md-right" id="checkout-button">Checkout</button>
                    </div>
                    <div class="alert alert-success mt-3">
                        <p class="icontext"><i class="icon text-success fa fa-truck"></i> Free Delivery within 1-2 weeks
                        </p>
                    </div>
                </div>
                {% else %}
                <div class="card-body border-top">
                    <a href="{% url 'index' %}" class="btn btn-primary float-md-right"> Nothing to Purchase Go back? <i
                            class="fa fa-chevron-right"></i> </a>
                    <a href="{% url 'index' %}" class="btn btn-light"> <i class="fa fa-chevron-left"></i> Continue shopping </a>
                </div>

                {% endif %}
            </main>
            <aside class="col-md-3">
                <div class="card mb-3">
                    <div class="card-body">
                        <form method="post">
                            {% include 'base/alert.html'%}
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Have coupon?</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="coupon" placeholder="Coupon code">
                                    <span class="input-group-append">
                                        <button type="submit" class="btn btn-primary">Apply</button>
                                    </span>
                                </div>
                            </div>
                            {% if cart.coupon %}
                            {% if cart.cart_items.all %}
                            <a href="{% url 'remove_coupon' cart.uid %}" class="btn btn-success">{{cart.coupon.coupon_code}}</a>
                            {% endif %}
                            {% endif %}
                        </form>

                    </div>
                    <!-- card-body.// -->
                    <div class="container mt-5">
                        <div class="form-group">
                            <label for="copyField">Coupons to apply</label>
                            <div class="input-group">
                                <input type="text" class="form-control" id="copyField1" value="FIRSTBUY" readonly>
                                <div class="input-group-append">
                                    <button class="btn btn-outline-primary" type="button" id="copyButton1">Copy</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> <!-- card .// -->
                <div class="card">
                    {% if cart.cart_items.all %}
                    <div class="card-body">
                        <dl class="dlist-align">
                            <b><dt>Total price:</dt></b>
                           <h4> <dd class="text-right">$ {{ cart.get_cart_total }} </dd></h4>
                        </dl>
                        <hr>
                        {% if cart.coupon %}
                        <dl class="dlist-align">
                            <h5><dt>hurray you saved  ${{cart.coupon.discount_price}} on your Purchase</dt></h5>
                            
                        </dl>
                        {% endif %}
                    {% else %}
                    <p>Buy something</p>
                    {% endif %}    
                        <hr>
                        <p class="text-center mb-3">
                            <img src="/media/images/misc/payments.png" height="26">
                        </p>
                    </div>
                </div>
            </aside>
        </div>
    </div>
    <div class="container mt-5">
        <div class="form-group">
            <label for="copyField">Card details for testing(any future date and cvv will work)</label>
            <div class="input-group">
                <input type="text" class="form-control" id="copyField" value="4242424242424242" readonly>
                <div class="input-group-append">
                    <button class="btn btn-outline-primary" type="button" id="copyButton">Copy</button>
                </div>
            </div>
        </div>
    </div>
    

    <script>
        document.getElementById('copyButton').addEventListener('click', function() {
            const copyText = document.getElementById('copyField');
            copyText.select();
            copyText.setSelectionRange(0, 99999); /* For mobile devices */
            document.execCommand('copy');
            alert('Copied the text: ' + copyText.value);
        });
    </script>
    <script>
        document.getElementById('copyButton1').addEventListener('click', function() {
            const copyText = document.getElementById('copyField1');
            copyText.select();
            copyText.setSelectionRange(0, 99999); /* For mobile devices */
            document.execCommand('copy');
            alert('Copied the text: ' + copyText.value);
        });
    </script>
    {% csrf_token %}
</section>

<script type="text/javascript">
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe("pk_test_51PUGUV2KHoy5iVMl8SRS3qMCE4Q05N4TJhxY6lyKt8UdBOUKiyHVuZ2nW3GlQVpsqcDv5GlsTqaEvnyChHAR2z7W001MoNfK6B");
    var checkoutButton = document.getElementById("checkout-button");
    
    checkoutButton.addEventListener("click", function () {
       
      fetch("{% url 'create-checkout-session'%}", {
        method: "POST",
        headers: {
            'X-CSRFToken': csrftoken
        }
        
      })
        .then(function (response) {
          return response.json();
        })
        .then(function (session) {
          return stripe.redirectToCheckout({ sessionId: session.id });
        })
        .then(function (result) {
          // If redirectToCheckout fails due to a browser or network
          // error, you should display the localized error message to your
          // customer using error.message.
          if (result.error) {
            alert(result.error.message);
          }
        })
        .catch(function (error) {
          console.error("Error:", error);
        });
    });

  </script> 







{% endblock %}

ecom/templates/accounts/profile.html
{% extends 'base/base.html' %}

{% block start %}
<div class="container mt-5">
    <h2 class="mb-4 ml-4 pl-4">Profile</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-3 text-center">
                {% if user.profile.profile_image %}
                    <img src="{{ user.profile.profile_image.url }}" class="img-profile border rounded-circle mb-3" alt="Profile Image" style="width: 150px; height: 150px;">
                {% else %}
                    <a href="#" class="icon icon-sm rounded-circle border"><i class="fa fa-user"></i></a>
                {% endif %}
                <div class="form-group">
                    {{ form.profile_image }}
                    
                    <button type="button" class="btn btn-secondary mt-2" onclick="document.getElementById('id_profile_image').click();">Upload Profile Image</button>
                </div>
            </div>
            <div class="col-md-9">
                <div class="form-group">
                    <label for="id_address_line_1">Address Line 1</label>
                    {{ form.address_line_1 }}
                </div>
                <div class="form-group">
                    <label for="id_address_line_2">Address Line 2</label>
                    {{ form.address_line_2 }}
                </div>
                <div class="form-group">
                    <label for="id_city">City</label>
                    {{ form.city }}
                </div>
                <div class="form-group">
                    <label for="id_state">State</label>
                    {{ form.state }}
                </div>
                <div class="form-group">
                    <label for="id_country">Country</label>
                    {{ form.country }}
                </div>
                <div class="form-group">
                    <label for="id_zip_code">Zip Code</label>
                    {{ form.zip_code }}
                </div>
                <a href="{% url 'index' %}" class="btn btn-primary">Go Back</a>
                <button type="submit" class="btn btn-primary">Save</button>
                
            </div>
        </div>
    </form>
</div>
<script>
    document.getElementById('id_profile_image').onchange = function() {
        document.getElementById('id_profile_image').form.submit();
    };
</script>
{% endblock %}

ecom/templates/accounts/track_status.html
{% extends 'base/base.html' %}

{% block start %}
<div class="container mt-4">
    <h2>Track Your Order</h2>
    <div class="row">
        {% for item in purchased_items %}
        <div class="col-md-12">
            <div class="card mb-3">
                <div class="row g-0">
                    <!-- <div class="col-md-4 d-flex justify-content-center align-items-center">
                        <img src="{{ item.product.product_images.first.image.url }}" class="img-sm img-responsive"  alt="Product Image">
                    </div> -->
                    <figure class="itemside col-md-4 d-flex justify-content-center align-items-center ">
                        <img
                                src="{{ item.product.product_images.first.image.url }}"
                                class="img-sm mt-4">
                       
                    </figure>
                    <div class="col-md-8">
                        <div class="card-body text-left">
                            <h5 class="card-title">{{ item.product.product_name }}</h5>
                            <p class="card-text">Status: <strong>{{ item.get_status_display }}</strong></p>
                            <p class="card-text">Price: ${{ item.get_product_price }}</p>
                            <p class="card-text">Color: {{ item.color_variant.color_name }}</p>
                            <p class="card-text">Size: {{ item.size_variant.size_name }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}